# fly.toml app configuration file generated for kmcphillips-duck on 2023-07-17T10:43:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kmcphillips-duck"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"

[env]
  APP_ENV = "production"
  DUCK_LOG_STDOUT = "true"

[processes]
  bot = "bin/bot"
  clockwork = "bundle exec clockwork clock.rb"

[[services]]
  protocol = "tcp"
  internal_port = 4444
  processes = ["bot"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
