# fly.toml file generated for kmcphillips-duck on 2022-11-06T19:12:38-05:00

app = "kmcphillips-duck"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DUCK_LOG_STDOUT = "true"

[build]
  builder = "heroku/buildpacks:20"

[deploy]
  strategy = "immediate"
  # release_command = "bundle exec ruby db_migration.rb"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  bot = "bundle exec ruby bot.rb"
  clockwork = "bundle exec clockwork clock.rb"

[[services]]
  processes = ["bot"]
  internal_port = 4444
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
