discord:
  token: XXXX
  debug_log: false

redis:
  url: redis://127.0.0.1:6379/0

web_auth:
  port: 9999
  username: XXX
  password: XXX

azure:
  key: XXX

giphy:
  key: XXX

wolfram_alpha:
  appid: XXX

twilio:
  outgoing_phone_number: "+12223334444"
  account_sid: XXX
  auth_token: XXX

openai:
  access_token: "XXXX"

duck:
  api_key: xxxxxxxxxxxxxxxxxxx

servers:
  server-name:
    users:
      -
        name: XXX
        username: XXX
        id: 123456767
        discriminator: 1234
        location: "Place, Province"
        phone_number: "+19998887777"
    tasks:
      daily_announcements:
        -
          day: 1
          month: 2 # omit for every month
          year: 2021 # omit for every year
          channel: XXX
          message: Oh, hello
        -
          weekday: Monday # instead of d/m/y trigger on a weekday or weekdays
          channel: XXX
          message: Oh, hello
